# Generated by Django 4.1.7 on 2023-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_candidate_number_student_candidate_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='candidate_code',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
